const express = require('express');
const app = express();
const server = require('http').Server(app); 
const { v4:uuidv4 } = require('uuid');

//to set in which format the file will be rendered
app.set('view engine', 'ejs');
app.use(express.static('public'));

//setting the response and request for this particular app along with particular string combination generated by uuid()
app.get('/', (req, res)=>{
    res.redirect(`/${uuidv4()}`);
})

app.get('/:room',(req, res)=>{
    res.render('room',{roomId: req.params.room})
})

//at 3030 the server can be listened
server.listen(3030);