const express = require('express');
const app = express();
const server = require('http').Server(app); 
const io = require('socket.io')(server) //defining the web socket for both way communication
const { v4:uuidv4 } = require('uuid');
const { ExpressPeerServer } = require('peer');
const peerServer = ExpressPeerServer(server, {
    debug: true
});

//to set in which format the file will be rendered
app.set('view engine', 'ejs');
app.use(express.static('public'));


app.use('/peerjs', peerServer);
//setting the response and request for this particular app along with particular string combination generated by uuid()
app.get('/', (req, res)=>{
    res.redirect(`/${uuidv4()}`);
})

app.get('/:room',(req, res)=>{
    res.render('room',{roomId: req.params.room})
})

//after getting broadcasted from "io.emit", io.on takes the control of broadcasted result and use it in "on" method
io.on('connection', socket =>{
    socket.on('join-room', (roomId, userId)=>{
        socket.join(roomId); //user will join by the particular roomID
        socket.broadcast.to(roomId).emit('user-connected', userId); //it's like a phonecall to give access of call over the websocket
    })
})

//at 3030 the server can be listened
server.listen(3030);